version: "3.9"

services:
  db:
    image: postgres:16
    container_name: sf_db
    environment:
      POSTGRES_DB: sistema_financeiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sf_backend
    environment:
      DB_ENGINE: postgres
      POSTGRES_DB: sistema_financeiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/sistema-financeiro-nfce
      dockerfile: Dockerfile
    container_name: sf_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:


