# Generated by Django 5.2.6 on 2025-10-21 17:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'indexes': [models.Index(fields=['tipo'], name='extrator_fi_tipo_82fffd_idx'), models.Index(fields=['ativo'], name='extrator_fi_ativo_39784f_idx')],
                'unique_together': {('descricao', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('FATURADO', 'Faturado')], max_length=10, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'indexes': [models.Index(fields=['cnpj_cpf'], name='extrator_fi_cnpj_cp_5b4f57_idx'), models.Index(fields=['tipo'], name='extrator_fi_tipo_d8533f_idx'), models.Index(fields=['ativo'], name='extrator_fi_ativo_ee66a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100, unique=True, verbose_name='Identificação')),
                ('tipo', models.CharField(choices=[('APAGAR', 'A Pagar'), ('ARECEBER', 'A Receber')], max_length=10, verbose_name='Tipo')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extrator_fiscal.classificacao', verbose_name='Classificação')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extrator_fiscal.pessoas', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Movimento de Contas',
                'verbose_name_plural': 'Movimentos de Contas',
            },
        ),
        migrations.CreateModel(
            name='ParcelaContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='extrator_fiscal.movimentocontas', verbose_name='Movimento')),
            ],
            options={
                'verbose_name': 'Parcela de Contas',
                'verbose_name_plural': 'Parcelas de Contas',
                'indexes': [models.Index(fields=['movimento'], name='extrator_fi_movimen_e4934e_idx'), models.Index(fields=['data_vencimento'], name='extrator_fi_data_ve_ceb834_idx'), models.Index(fields=['status'], name='extrator_fi_status_b6352a_idx'), models.Index(fields=['ativo'], name='extrator_fi_ativo_ef01fa_idx')],
                'unique_together': {('movimento', 'numero_parcela')},
            },
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['tipo'], name='extrator_fi_tipo_aece1c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['pessoa'], name='extrator_fi_pessoa__9160cb_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['classificacao'], name='extrator_fi_classif_f9b88f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['ativo'], name='extrator_fi_ativo_8822ef_idx'),
        ),
    ]
