# Generated by Django 5.2.6 on 2025-10-22 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator_fiscal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classificacao',
            name='extrator_fi_ativo_39784f_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentocontas',
            name='extrator_fi_pessoa__9160cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentocontas',
            name='extrator_fi_classif_f9b88f_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentocontas',
            name='extrator_fi_ativo_8822ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='parcelacontas',
            name='extrator_fi_ativo_ef01fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='pessoas',
            name='extrator_fi_ativo_ee66a3_idx',
        ),
        migrations.RenameIndex(
            model_name='pessoas',
            new_name='extrator_fi_documen_6e1712_idx',
            old_name='extrator_fi_cnpj_cp_5b4f57_idx',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='movimentocontas',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='movimentocontas',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='movimentocontas',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='parcelacontas',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='ativo',
        ),
        migrations.AddField(
            model_name='classificacao',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=45, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='classificacoes',
            field=models.ManyToManyField(related_name='movimentos', to='extrator_fiscal.classificacao', verbose_name='Classificações'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='faturado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_como_faturado', to='extrator_fiscal.pessoas', verbose_name='Pessoa (Faturado)'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='fornecedor_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_como_fornecedor', to='extrator_fiscal.pessoas', verbose_name='Pessoa (Fornecedor/Cliente)'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=45, verbose_name='Número Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=45, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='parcelacontas',
            name='identificacao',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Identificação'),
        ),
        migrations.AddField(
            model_name='parcelacontas',
            name='valor_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Saldo'),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='fantasia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fantasia'),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=45, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='parcelacontas',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=45, verbose_name='Status Parcela'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cnpj_cpf',
            field=models.CharField(db_column='documento', max_length=45, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='razao_social',
            field=models.CharField(max_length=150, verbose_name='Razão Social'),
        ),
        migrations.AddIndex(
            model_name='classificacao',
            index=models.Index(fields=['status'], name='extrator_fi_status_fc1e71_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['fornecedor_cliente'], name='extrator_fi_fornece_2569f4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['faturado'], name='extrator_fi_faturad_69a40c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['status'], name='extrator_fi_status_5a6df4_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoas',
            index=models.Index(fields=['status'], name='extrator_fi_status_12ba16_idx'),
        ),
    ]
